# middleman deploy standard streams go to dev null to hide sensitive
# information like the GitHub Token

language: ruby
rvm:
  - "2.2.3"
bundler_args: --path gems
cache: bundler


before_script:
  - git config --global user.name ${GH_NAME}
  - git config --global user.email ${GH_EMAIL}

# If build, test or deploy fails, build is stopped and does not carry on.
script:
  - bundle exec middleman build --verbose && bundle exec rake test && bundle exec middleman deploy &> /dev/null

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
